---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mutuajames.github.io.my.domain
  resources:
  - replicachangelisteners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mutuajames.github.io.my.domain
  resources:
  - replicachangelisteners/finalizers
  verbs:
  - update
- apiGroups:
  - mutuajames.github.io.my.domain
  resources:
  - replicachangelisteners/status
  verbs:
  - get
  - patch
  - update
