{{- if and .Values.clusterRole.create .Values.serviceAccount.create }}
apiVersion: apps/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "replicachange-operator.fullname" . }}
  labels:
    {{- include "replicachange-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "replicachange-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "replicachange-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}